name: Sync changes

on:
  push:
    branches:
      - master

jobs:
  glitch:
    runs-on: ubuntu-latest
    steps:
      -
        name: Sync to Glitch project
        uses: kanadgupta/glitch-sync@v1.1
        with:
          project-id: '${{ secrets.projectId }}'
          auth-token: '${{ secrets.authToken }}'

  gh-pages:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build & deploy to github
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          make dist deploy ROOT=${GITHUB_REPOSITORY/$GITHUB_REPOSITORY_OWNER/}
